Add Cygwin CI, lint, and robust tests

diff --git a/test/dbdSensors b/test/dbdSensors
--- a/test/dbdSensors
+++ b/test/dbdSensors
@@ -8,8 +8,8 @@
 CMD=../bin/dbdSensors
 TMP=../tmp
 
-if [ ! -x $CMD ] ; then
-  echo $CMD is not executable
+if [ ! -x "$CMD" ] ; then
+  echo "$CMD is not executable"
   exit 1
 fi
 
@@ -18,8 +18,8 @@ if ! diff --version >/dev/null ; then
   exit 1
 fi
 
-if ! mkdir -p $TMP ; then
-  echo Unable to create $TMP
+if ! mkdir -p "$TMP" ; then
+  echo "Unable to create $TMP"
   exit 1
 fi
 
@@ -28,32 +28,32 @@ doCompare() {
   ref=$1
   shift
 
-  if [ ! -e $ref ] ; then
-    echo Reference file $ref does not exist
+  if [ ! -e "$ref" ] ; then
+    echo "Reference file $ref does not exist"
     exit 1
   fi
 
-  for file in $* ; do
-    if [ ! -e $file ] ; then
-      echo Dinkum Binary Data file $file does not exist
+  for file in "$@" ; do
+    if [ ! -e "$file" ] ; then
+      echo "Dinkum Binary Data file $file does not exist"
       exit 1
     fi
   done
 
-  if ! $CMD -o $tmpfn $* ; then
-    echo Failed to execute $CMD on $*
-    rm -f $tmpfn
+  if ! "$CMD" -o "$tmpfn" "$@" ; then
+    echo "Failed to execute $CMD on $*"
+    rm -f "$tmpfn"
     exit 1
   fi
 
-  if ! diff -q $tmpfn $ref ; then
-    echo Failed on comparison of $* sensors
-    diff $tmpfn $ref
-    rm -f $tmpfn
+  if ! diff -q "$tmpfn" "$ref" ; then
+    echo "Failed on comparison of $* sensors"
+    diff "$tmpfn" "$ref"
+    rm -f "$tmpfn"
     exit 1
   fi
 
-  rm -f $tmpfn
+  rm -f "$tmpfn"
 }
 
 doCompare test.sbd.sensors test.sbd
diff --git a/test/pd02netCDF b/test/pd02netCDF
--- a/test/pd02netCDF
+++ b/test/pd02netCDF
@@ -8,19 +8,19 @@
 CMD=../bin/pd02netCDF
 TMP=../tmp
 
-if [ ! -x $CMD ] ; then
-  echo $CMD is not executable
+if [ ! -x "$CMD" ] ; then
+  echo "$CMD is not executable"
   exit 1
 fi
 
-if ! mkdir -p $TMP ; then
-  echo Unable to create $TMP
+if ! mkdir -p "$TMP" ; then
+  echo "Unable to create $TMP"
   exit 1
 fi
 
 chkCMD() {
-  if ! $* </dev/null >/dev/null 2>&1; then
-    echo No $1 command found
+  if ! "$@" </dev/null >/dev/null 2>&1; then
+    echo "No $1 command found"
     exit 1
   fi
 }
@@ -33,50 +33,50 @@ doCompare() {
   ref=$1
   shift
 
-  if [ ! -e $ref ] ; then
-    echo Reference file $ref does not exist
+  if [ ! -e "$ref" ] ; then
+    echo "Reference file $ref does not exist"
     exit 1
   fi
 
-  for file in $* ; do
-    if [ ! -e $file ] ; then
-      echo Dinkum Binary Data file $file does not exist
+  for file in "$@" ; do
+    if [ ! -e "$file" ] ; then
+      echo "Dinkum Binary Data file $file does not exist"
       exit 1
     fi
   done
 
-  if ! $CMD -o $tmpfn $* ; then
-    echo Failed to execute $CMD on $*
-    rm -f $tmpfn
+  if ! "$CMD" -o "$tmpfn" "$@" ; then
+    echo "Failed to execute $CMD on $*"
+    rm -f "$tmpfn"
     exit 1
   fi
 
-  if ! ncdump $tmpfn >$tmp1fn ; then
-    echo Failed to execute ncdump on $tmpfn
-    rm -f $tmpfn $tmp1fn $tmp2fn
+  if ! ncdump "$tmpfn" >"$tmp1fn" ; then
+    echo "Failed to execute ncdump on $tmpfn"
+    rm -f "$tmpfn" "$tmp1fn" "$tmp2fn"
     exit 1
   fi
 
-  if ! tail -n +2 $tmp1fn >$tmp2fn ; then # Get rid of first line which contains filename
-    echo Failed to execute tail on $tmp1fn
-    rm -f $tmpfn $tmp1fn $tmp2fn
+  if ! tail -n +2 "$tmp1fn" >"$tmp2fn" ; then # Get rid of first line which contains filename
+    echo "Failed to execute tail on $tmp1fn"
+    rm -f "$tmpfn" "$tmp1fn" "$tmp2fn"
     exit 1
   fi
 
-  if ! tail -n +2 $ref >$tmp1fn ; then # Get rid of first line which contains filename
-    echo Failed to execute tail on $ref
-    rm -f $tmpfn $tmp1fn $tmp2fn
+  if ! tail -n +2 "$ref" >"$tmp1fn" ; then # Get rid of first line which contains filename
+    echo "Failed to execute tail on $ref"
+    rm -f "$tmpfn" "$tmp1fn" "$tmp2fn"
     exit 1
   fi
 
-  if ! diff -q $tmp2fn $tmp1fn ; then
-    echo Failed on comparison of $* sensors
-    diff $tmp2fn $tmp1fn
-    rm -f $tmpfn $tmp1fn $tmp2fn
+  if ! diff -q "$tmp2fn" "$tmp1fn" ; then
+    echo "Failed on comparison of $* sensors"
+    diff "$tmp2fn" "$tmp1fn"
+    rm -f "$tmpfn" "$tmp1fn" "$tmp2fn"
     exit 1
   fi
 
-  rm -f $tmpfn $tmp1fn $tmp2fn
+  rm -f "$tmpfn" "$tmp1fn" "$tmp2fn"
 }
 
 chkCMD diff --version
